### Get all
GET http://localhost:8080/api/v1/appointments

### Get by patient Id
GET http://localhost:8080/api/v1/appointments?patientId=1

### Get by doctor Id
GET http://localhost:8080/api/v1/appointments?doctorId=1

### Create appointment
POST http://localhost:8080/api/v1/appointments
Content-Type: application/json

{
  "doctorId": "1",
  "patientId": "1",
  "reason": "dsaf",
  "date": "fdsf",
  "time": "34fgg"
}








### Delete appointment
DELETE http://localhost:8080/api/v1/appointments/5
